### ISSUE TITLE
setup.py unconditionally downloads *.egg from the Internet

### ISSUE THREAD

**Issue by 0xABD** [frida/frida-python#55]
setup.py as implemented currently always downloads the main frida *.egg file from the Internet.
For offline firewalled installations of frida-python we need to either:
* build a wheel (e.g. built at the end of the online setup.py actions and stored in a temp folder)
* install the missing egg manually
* modify the setup.py to search for the egg file e.g. in the current folder (dirty hack as in https://github.com/frida/frida-python/pull/54)

**Comment by oleavr** [comment]
Good point!

A side-note regarding wheels; I almost switched from .egg to wheel but realized in the last minute that wheels don't provide a binary package solution for Linux, only Windows and OS X. I was also considering making setup.py build the extension and Frida, but due to code-signing requirements (Mac) and Visual Studio requirement (Windows), I hesitated to go down that road.

I think your fallback approach in #54 is a handy solution to have an emergency path for offline/firewalled installations.

**Comment by oleavr** [comment]
Considering this fixed.
